schema_version = "1.0.0"
id = "harhtools"
version = "1.0.1"
name = "harhtools"
tagline = "Build shapes from planar wires and align objects"
maintainer = "harhtools"
type = "add-on"
tags = ["Mesh", "Object"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]

[build]
paths = ["__init__.py", "shape_builder.py", "centering.py", "README.md", "LICENSE"]
